### PR TITLE
made the navbar responsive

### PR DESCRIPTION
**Pull request by Godwindaniel10**
made the nav bar responsive to all devices

### CODE REVIEW

**Review by sonuishaq67 — APPROVED** [review]
LGTM on phone 
@Pranay0302 how's it working in pc

**Comment by Pranay0302** [comment]
@Godwindaniel10 after the auth part, the settings button in the navbar doesn't look good. 
I'll make the changes later to make it look better.
Thank you for contributing.

**Comment by Pranay0302** [comment]
@Godwindaniel10 after the auth part, the settings button in the navbar doesn't look good.
I'll make the changes later to make it look better.
Thank you for contributing.

**Comment by Godwindaniel10** [comment]
my pleasure @Pranay0302 , so happy to contribute...

**Pull request merged**
